// Rename the file to config.js

config = {};

config.mongodb = {};
config.category = {};
config.apis = {};

config.mongodb.connectionString = "{SET YOUR DB CONN STRING}"
config.mongodb.centralDB = "saas_sca";
config.mongodb.collections = {};

config.apis.clusteringServiceEndpoint = "{SET CLUSTERING SERVICE ENDPOINT}";

config.mongodb.collections.CatAGov = "CatAGov";
config.mongodb.collections.CatAOps = "CatAOps";
config.mongodb.collections.CatBGov = "CatBGov";
config.mongodb.collections.CatBOps = "CatBOps";
config.mongodb.collections.CatCGov = "CatCGov";
config.mongodb.collections.CatCOps = "CatCOps";
config.mongodb.collections.CatDGov = "CatDGov";
config.mongodb.collections.CatDOps = "CatDOps";

config.category.CatAGov = "CatAGov";
config.category.CatAOps = "CatAOps";
config.category.CatBGov = "CatBGov";
config.category.CatBOps = "CatBOps";
config.category.CatCGov = "CatCGov";
config.category.CatCOps = "CatCOps";
config.category.CatDGov = "CatDGov";
config.category.CatDOps = "CatDOps";

config.category.CatAGovRecommendationBest = "You are complaint in SaaS cloud Identity Management - Governance related controls in most popular regulatory compliance standards. You have a low risk of security incidents related to the identity management area of your SaaS application. Recommend referring to the Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3.A - Assessing the SaaS cloud Identity Management section, following the proposed 5 step subprocess, and going through the process annually.";
config.category.CatAGovRecommendationMedium = "You are not compliant with mandatory controls required in the SaaS cloud Identity Management - Governance section and lack complete compliance with most popular regulatory compliance standards. You have a medium to high risk of security incidents related to the identity management area of your SaaS application. There is room for improvement in the Identity management side to better compliance and security. Refer Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3.A - Assessing the SaaS cloud Identity Management section and following the proposed 5 step subprocess.";
config.category.CatAGovRecommendationWorst = "You are not compliant in any SaaS cloud Identity Management - Governance related controls in most popular regulatory compliance standards. You have a critical risk of security incidents related to the identity management area of your SaaS application. It would be best if you put a considerable effort into improving the status of your SaaS product compliancy and security related to the Identity management side. Highly recommend referring to Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3.A - Assessing the SaaS cloud Identity Management section and following the proposed 5 step subprocess.";
config.category.CatAOpsRecommendationBest = "You are complaint in SaaS cloud Identity Management - Operations related controls in most popular regulatory compliance standards. You have a low risk of security incidents related to the identity management area of your SaaS application. Recommend referring to the Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3.A - Assessing the SaaS cloud Identity Management section, following the proposed 5 step subprocess, and going through the process annually.";
config.category.CatAOpsRecommendationMedium = "You are not compliant with mandatory controls required in the SaaS cloud Identity Management - Operations section and lack complete compliance with the most popular regulatory compliance standards. You have a medium to high risk of security incidents related to the identity management area of your SaaS application. There is room for improvement in the Identity management side to better compliance and security. Refer Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3.A - Assessing the SaaS cloud Identity Management section and following the proposed 5 step subprocess.";
config.category.CatAOpsRecommendationWorst = "You are not compliant in any SaaS cloud Identity Management - Operations related controls in most popular regulatory compliance standards. You have a critical risk of security incidents related to the identity management area of your SaaS application. It would be best if you put a considerable effort into improving the status of your SaaS product compliancy and security related to the Identity management side. Highly recommend referring to Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3.A - Assessing the SaaS cloud Identity Management section and following the proposed 5 step subprocess.";
config.category.CatBGovRecommendationBest = "You are complaint in SaaS Cloud Metastructure - Governance related controls in most popular regulatory compliance standards. You have a low risk of security incidents related to the metastructure area of your SaaS application. Recommend referring to the Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. B - Assessing the SaaS cloud Metastructure section, following the proposed 5 step subprocess, and going through the process annually.";
config.category.CatBGovRecommendationMedium = "";
config.category.CatBGovRecommendationWorst = "You are not compliant in SaaS Cloud Metastructure - Governance related controls in most popular regulatory compliance standards. You have a high/critical risk of security incidents related to the metastructure area of your SaaS application. It would be best if you put a considerable effort into improving the status of your SaaS product compliancy and security related to the metastructure side. Highly recommend referring to Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. B - Assessing the SaaS cloud Metastructure section, following the proposed 5 step subprocess.";
config.category.CatBOpsRecommendationBest = "You are complaint in SaaS Cloud Metastructure - Operations related controls in most popular regulatory compliance standards. You have a low risk of security incidents related to the metastructure area of your SaaS application. Recommend referring to the Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. B - Assessing the SaaS cloud Metastructure section, following the proposed 5 step subprocess, and going through the process annually.";
config.category.CatBOpsRecommendationMedium = "You are not compliant with mandatory controls required in the SaaS Cloud Metastructure - Operations section and lack complete compliance with the most popular regulatory compliance standards. You have a medium to high risk of security incidents related to the metastructure area of your SaaS application. There is room for improvement in the metastructure side to better compliance and security. Refer Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. B - Assessing the SaaS cloud Metastructure section, following the proposed 5 step subprocess.";
config.category.CatBOpsRecommendationWorst = "You are not compliant in SaaS Cloud Metastructure - Operations related controls in most popular regulatory compliance standards. You have a critical risk of security incidents related to the metastructure area of your SaaS application. It would be best if you put a considerable effort into improving the status of your SaaS product compliancy and security related to the metastructure side. Highly recommend referring to Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. B - Assessing the SaaS cloud Metastructure section, following the proposed 5 step subprocess.";
config.category.CatCGovRecommendationBest = "You are complaint in SaaS Cloud Applistructure & Infostructure - Governance related controls in most popular regulatory compliance standards. You have a low risk of security incidents related to your SaaS application's Applistructure & Infostructure area. Recommend referring to the Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. C - Assessing the SaaS cloud Applistructure & Infostructure section, following the proposed 5 step subprocess, and going through the process annually.";
config.category.CatCGovRecommendationMedium = "You are not compliant with mandatory controls required in the SaaS Cloud Applistructure & Infostructure - Governance section and lack complete compliance with most popular regulatory compliance standards. You have a medium to high risk of security incidents to your SaaS application's Applistructure & Infostructure area. There is room for improvement in the Applistructure & Infostructure side to better compliance and security. Refer Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. C - Assessing the SaaS cloud Applistructure & Infostructure section, following the proposed 5 step subprocess.";
config.category.CatCGovRecommendationWorst = "You are not compliant in SaaS Cloud Applistructure & Infostructure - Governance related controls in most popular regulatory compliance standards. You have a high risk of security incidents related to your SaaS application's Applistructure & Infostructure area. It would be best if you put a considerable effort into improving the status of your SaaS product compliancy and security related to the Applistructure & Infostructure side. Highly recommend referring to Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. C - Assessing the SaaS cloud Applistructure & Infostructure section, following the proposed 5 step subprocess.";
config.category.CatCOpsRecommendationBest = "You are complaint in SaaS Cloud Applistructure & Infostructure - Operations related controls in most popular regulatory compliance standards. You have a low risk of security incidents related to your SaaS application's Applistructure & Infostructure area. Recommend referring to the Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. C - Assessing the SaaS cloud Applistructure & Infostructure section, following the proposed 5 step subprocess, and going through the process annually.";
config.category.CatCOpsRecommendationMedium = "You are not compliant with mandatory controls required in the SaaS Cloud Applistructure & Infostructure - Operations section and lack complete compliance with the most popular regulatory compliance standards. You have a medium to high risk of security incidents related to your SaaS application's Applistructure & Infostructure area. There is room for improvement in the Applistructure & Infostructure side to better compliance and security. Refer Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. C - Assessing the SaaS cloud Applistructure & Infostructure section, following the proposed 5 step subprocess.";
config.category.CatCOpsRecommendationWorst = "You are not compliant in SaaS Cloud Applistructure & Infostructure - Operations related controls in most popular regulatory compliance standards. You have a high risk of security incidents related to the Applistructure & Infostructure area. It would be best if you put a considerable effort into improving the status of your SaaS product compliancy and security related to the Applistructure & Infostructure side. Highly recommend referring to Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. C - Assessing the SaaS cloud Applistructure & Infostructure section, following the proposed 5 step subprocess.";
config.category.CatDGovRecommendationBest = "You are complaint in SaaS Cloud Infrastructure - Governance related controls in most popular regulatory compliance standards. You have a low risk of security incidents related to the infrastructure area of your SaaS application. Recommend referring to the Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. D - Assessing the SaaS cloud Infrastructure section, following the proposed 5 step subprocess, and going through the process annually.";
config.category.CatDGovRecommendationMedium = "You are not compliant with mandatory controls required in the SaaS Cloud Infrastructure - Governance section and lack complete compliance with most popular regulatory compliance standards. You have a medium to high risk of security incidents related to the infrastructure area of your SaaS application. There is room for improvement on the infrastructure side to better compliance and security. Refer Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. D - Assessing the SaaS cloud Infrastructure section, following the proposed 5 step subprocess.";
config.category.CatDGovRecommendationWorst = "You are not compliant in SaaS Cloud Infrastructure - Governance related controls in most popular regulatory compliance standards. You have a high risk of security incidents related to the infrastructure area of your SaaS application. It would be best if you put a considerable effort into improving the status of your SaaS product compliancy and security related to the infrastructure side. Highly recommend referring to Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. D - Assessing the SaaS cloud Infrastructure section, following the proposed 5 step subprocess.";
config.category.CatDOpsRecommendationBest = "You are complaint in SaaS Cloud Infrastructure - Operations related controls in most popular regulatory compliance standards. You have a low risk of security incidents related to the infrastructure area of your SaaS application. Recommend referring to the Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. D - Assessing the SaaS cloud Infrastructure section, following the proposed 5 step subprocess, and going through the process annually.";
config.category.CatDOpsRecommendationMedium = "You are not compliant with mandatory controls required in the SaaS Cloud Infrastructure - Operations section and lack complete compliance with the most popular regulatory compliance standards. You have a medium to high risk of security incidents related to the infrastructure area of your SaaS application. There is room for improvement on the infrastructure side to better compliance and security. Refer Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. D - Assessing the SaaS cloud Infrastructure section, following the proposed 5 step subprocess.";
config.category.CatDOpsRecommendationWorst = "You are not compliant in SaaS Cloud Infrastructure - Operations related controls in the most popular regulatory compliance standards. You have a high risk of security incidents related to the infrastructure area of your SaaS application. It would be best if you put a considerable effort into improving the status of your SaaS product compliancy and security related to the infrastructure side. Highly recommend referring to Enhanced Cloud Security and Compliance Reference Model for Emerging SaaS Cloud Systems consuming Public cloud services - 3. D - Assessing the SaaS cloud Infrastructure section, following the proposed 5 step subprocess.";

module.exports = config;